basicCRM/Models/DBObjects/Opportunity.cs
using System;
using System.Collections.Generic;

namespace basicCRM.Models.DBObjects
{
    public partial class Opportunity
    {
        public Opportunity()
        {
            Offers = new HashSet<Offer>();
        }

        public Guid Idopportunity { get; set; }
        public string Name { get; set; } = null!;
        public Guid Idcustomer { get; set; }
        public string? CommodityType { get; set; }
        public Guid Idemployee { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public string? Status { get; set; }

        public virtual Customer IdcustomerNavigation { get; set; } = null!;
        public virtual Employee IdemployeeNavigation { get; set; } = null!;
        public virtual ICollection<Offer> Offers { get; set; }
    }
}

basicCRM/Controllers/OpportunityController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using basicCRM.Repository;
using basicCRM.Data;
using basicCRM.Models;
using basicCRM.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace basicCRM.Controllers
{
    [Authorize(Roles = "HeadOfSales,Sales,AccountManager")]
    public class OpportunityController : Controller
    {

        private OpportunityRepository _opportunityRepository;
        private EmployeeRepository _employeeRepository;
        private CustomerRepository _customerRepository;
        
        public List<String> lcommoditytype = new List<String>() { "Gas","Power","Gas&Power"};
        public List<String> lstatus = new List<String>() { "Won", "Lost", "Open" };

        public OpportunityController(ApplicationDbContext _DBContext)
        { 
            _opportunityRepository= new OpportunityRepository(_DBContext);
            _employeeRepository= new EmployeeRepository(_DBContext);
            _customerRepository= new CustomerRepository(_DBContext);    
        }


        // GET: OpportunityController
        public ActionResult Index(string searchString,int page = 1)
        {
            var list = _opportunityRepository.GetAllOpportunities();
            int pageSize = 4;

            int recordsSkip = (page - 1) * pageSize;
            int recordsCount = list.Count();
            if (!String.IsNullOrEmpty(searchString))
            {
                list = _opportunityRepository.GetAllOpportunitiesFilteredBy(searchString);
                recordsSkip = 0;
            }
            var viewmodellist = new List<OpportunityViewModelIndexDetails>();
            foreach (var opportunity in list)
            {
                viewmodellist.Add(new OpportunityViewModelIndexDetails(opportunity, _customerRepository,_employeeRepository));
            }
            var pager = new Pager(recordsCount, page, pageSize);
            var data = viewmodellist.Skip(recordsSkip).Take(pager.PageSize);
            this.ViewBag.Pager = pager;
            return View(data);
        }

        // GET: OpportunityController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _opportunityRepository.GetOpportunityByID(id);
            var viewmodel = new OpportunityViewModelIndexDetails(model, _customerRepository, _employeeRepository);
            return View("DetailsOpportunity", viewmodel);
        }

        // GET: OpportunityController/Create
        public ActionResult Create()
        {

            ViewBag.commoditytypes = lcommoditytype;
            ViewBag.statuses = lstatus;
            var viewmodel = new OpportunityViewModelCreateEdit(new OpportunityModel(),_customerRepository, _employeeRepository);
            return View("CreateOpportunity",viewmodel);
        }

        // POST: OpportunityController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var model = new OpportunityModel();
                var task = TryUpdateModelAsync(model);
                if(task.Result)
                {
                    _opportunityRepository.InsertOpportunity(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("CreateOpportunity");
            }
        }

        // GET: OpportunityController/Edit/5
        public ActionResult Edit(Guid id)
        {
            ViewBag.commoditytypes = lcommoditytype;
            ViewBag.statuses = lstatus;
            var model = _opportunityRepository.GetOpportunityByID(id);
            var viewmodel = new OpportunityViewModelCreateEdit(model, _customerRepository, _employeeRepository);  
            return View("EditOpportunity",viewmodel);
        }

        // POST: OpportunityController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, IFormCollection collection)
        {
            try
            {
                var model = new OpportunityModel();
                var task = TryUpdateModelAsync(model);
                model.Idopportunity=id;
                if (task.Result)
                {
                    _opportunityRepository.UpdateOpportunity(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("EditOpportunity");
            }
        }
        [Authorize(Roles = "HeadOfSales,AccountManager")]
        // GET: OpportunityController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model= _opportunityRepository.GetOpportunityByID(id);
            var viewmodel = new OpportunityViewModelCreateEdit(model, _customerRepository, _employeeRepository);
            ViewBag.ErrorMessage = "Aceasta oportunitate este legat de o oferta si nu se poate sterge";
            return View("DeleteOpportunity",viewmodel);
        }

        [Authorize(Roles = "HeadOfSales,AccountManager")]
        // POST: OpportunityController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                _opportunityRepository.DeleteOpportunity(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("DeleteOpportunity", id);
            }
        }
    }
}

basicCRM/Views/Opportunity/CreateOpportunity.cshtml
@model basicCRM.ViewModels.OpportunityViewModelCreateEdit

@{
    ViewData["Title"] = "CreateOpportunity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Opportunity</h1>

@*<h4>OpportunityViewModelExtended</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
@*            <div class="form-group">
                <label asp-for="Idopportunity" class="control-label"></label>
                <input asp-for="Idopportunity" class="form-control" />
                <span asp-validation-for="Idopportunity" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
@*            <div class="form-group">
                <label asp-for="Idcustomer" class="control-label"></label>
                <input asp-for="Idcustomer" class="form-control" />
                <span asp-validation-for="Idcustomer" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="CommodityType" class="control-label"></label>
                @*<input asp-for="CommodityType" class="form-control" />*@
                @Html.DropDownList("CommodityType", new SelectList(ViewBag.commoditytypes, "", ""),"",new{@class="form-control"})
                @*<span asp-validation-for="CommodityType" class="text-danger"></span>*@
            </div>
@*            <div class="form-group">
                <label asp-for="Idemployee" class="control-label"></label>
                <input asp-for="Idemployee" class="form-control" />
                <span asp-validation-for="Idemployee" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="ValidFrom" class="control-label"></label>
                <input asp-for="ValidFrom" class="form-control" />
                <span asp-validation-for="ValidFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValidTo" class="control-label"></label>
                <input asp-for="ValidTo" class="form-control" />
                <span asp-validation-for="ValidTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                @*<input asp-for="Status" class="form-control" />*@
                @Html.DropDownList("Status", new SelectList(ViewBag.statuses, "", ""),"",new{@class="form-control"})
                @*<span asp-validation-for="Status" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="Owner" class="control-label"></label>
                <select asp-for="Idemployee" class="form-control" />
                @foreach (var obj in Model.Employees)
                {
                    <option value="@obj.Idemployee">@obj.Name</option>
                }
                </select>
                <span asp-validation-for="Owner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer" class="control-label"></label>
                <select asp-for="Idcustomer" class="form-control" />
                @foreach (var obj in Model.Customers)
                {
                    <option value="@obj.Idcustomer">@obj.Name</option>
                }
                </select>
                <span asp-validation-for="Customer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

basicCRM/Views/Opportunity/DeleteOpportunity.cshtml
@model basicCRM.ViewModels.OpportunityViewModelIndexDetails

@{
    ViewData["Title"] = "DeleteOpportunity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete Opportunity</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    @*<h4>OpportunityViewModel</h4>*@
    <hr />
    <dl class="row">
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idopportunity)
        </dt>*@
@*        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idopportunity)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idcustomer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idcustomer)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CommodityType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CommodityType)
        </dd>
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idemployee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idemployee)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValidFrom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValidFrom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValidTo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValidTo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer)
        </dd>
    </dl>
    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger">
            @ViewBag.ErrorMessage
        </div>
    }

    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

basicCRM/Views/Opportunity/DetailsOpportunity.cshtml
@model basicCRM.ViewModels.OpportunityViewModelIndexDetails

@{
    ViewData["Title"] = "DetailsOpportunity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Opportunity Details</h1>

<div>
    @*<h4>OpportunityViewModel</h4>*@
    <hr />
    <dl class="row">
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idopportunity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idopportunity)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idcustomer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idcustomer)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CommodityType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CommodityType)
        </dd>
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idemployee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idemployee)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValidFrom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValidFrom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValidTo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValidTo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Idopportunity }) |
    <a asp-action="Index">Back to List</a>
</div>

basicCRM/Views/Opportunity/EditOpportunity.cshtml
@model basicCRM.ViewModels.OpportunityViewModelCreateEdit

@{
    ViewData["Title"] = "EditOpportunity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Opportunity</h1>

@*<h4>OpportunityViewModelExtended</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
@*            <div class="form-group">
                <label asp-for="Idopportunity" class="control-label"></label>
                <input asp-for="Idopportunity" class="form-control" />
                <span asp-validation-for="Idopportunity" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
@*            <div class="form-group">
                <label asp-for="Idcustomer" class="control-label"></label>
                <input asp-for="Idcustomer" class="form-control" />
                <span asp-validation-for="Idcustomer" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="CommodityType" class="control-label"></label>
                @*<input asp-for="CommodityType" class="form-control" />*@
                @Html.DropDownList("CommodityType", new SelectList(ViewBag.commoditytypes, "", ""),"",new{@class="form-control"})
                @*<span asp-validation-for="CommodityType" class="text-danger"></span>*@
            </div>
@*            <div class="form-group">
                <label asp-for="Idemployee" class="control-label"></label>
                <input asp-for="Idemployee" class="form-control" />
                <span asp-validation-for="Idemployee" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="ValidFrom" class="control-label"></label>
                <input asp-for="ValidFrom" class="form-control" />
                <span asp-validation-for="ValidFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValidTo" class="control-label"></label>
                <input asp-for="ValidTo" class="form-control" />
                <span asp-validation-for="ValidTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                @*<input asp-for="Status" class="form-control" />*@
                @Html.DropDownList("Status", new SelectList(ViewBag.statuses, "", ""),"",new{@class="form-control"})
                @*<span asp-validation-for="Status" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="Owner" class="control-label"></label>
                <select asp-for="Idemployee" class="form-control" />
                @foreach (var obj in Model.Employees)
                {
                    <option value="@obj.Idemployee">@obj.Name</option>
                }
                </select>
                <span asp-validation-for="Owner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer" class="control-label"></label>
                <select asp-for="Idcustomer" class="form-control" />
                @foreach (var obj in Model.Customers)
                {
                        <option value="@obj.Idcustomer">@obj.Name</option>
                }
                </select>
                <span asp-validation-for="Customer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

basicCRM/Views/Opportunity/Index.cshtml
@model IEnumerable<basicCRM.ViewModels.OpportunityViewModelIndexDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Pager pager = new Pager();
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
    }
}

<h1>List of Opportunities</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>
@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CommodityType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValidFrom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValidTo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Owner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CommodityType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValidFrom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValidTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Owner)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id=item.Idopportunity },new {@class="btn btn-success"})*@
                    <a href="@Url.Action("Edit","Opportunity",new { id=item.Idopportunity})" ,new class="btn btn-outline-warning">
                            <span>
                                <img src="~/pencil-square.svg" alt="Edit SVG" />
                            </span>
                        </a>
                @*@Html.ActionLink("Details", "Details", new { id=item.Idopportunity },new {@class="btn btn-info"})*@
                    <a href="@Url.Action("Details","Opportunity",new { id=item.Idopportunity})" ,new class="btn btn-outline-info">
                            <span>
                                <img src="~/card-heading.svg" alt="Details SVG" />
                            </span>
                                </a>
                @*@Html.ActionLink("Delete", "Delete", new { id=item.Idopportunity },new {@class="btn btn-danger"})*@
                    <a href="@Url.Action("Delete","Opportunity",new { id=item.Idopportunity})" ,new class="btn btn-outline-danger">
                        <span>
                            <img src="~/trash.svg" alt="Delete SVG" />
                        </span>
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>

<div class="container">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">

            @if (pager.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-asp-controller="Opportunity" asp-action="Index" asp-route-page="1">First</a>
                </li>
                <li>
                    <a class=" page-link" asp-asp-controller="Opportunity" asp-action="Index" asp-route-page="@(pager.CurrentPage-1)">Previous</a>
                </li>
            }

            @for (var pge = 1; pge <= pager.TotalPages; pge++)
            {
                <li class="page-item @(pge==pager.CurrentPage ? "active" : "")">

                    <a class="page-link" asp-controller="Opportunity" asp-action="Index" asp-route-page="@pge"> @pge </a>
                </li>

            }

            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li class="page-item">
                    <a class=" page-link" asp-asp-controller="Opportunity" asp-action="Index" asp-route-page="@(pager.CurrentPage+1)">Next</a>
                </li>
                <li>
                    <a class=" page-link" asp-asp-controller="Opportunity" asp-action="Index" asp-route-page="@(pager.TotalPages)">Last</a>
                </li>

            }

        </ul>

    }

</div>