basicCRM/Models/DBObjects/ContactPerson.cs
using System;
using System.Collections.Generic;

namespace basicCRM.Models.DBObjects
{
    public partial class ContactPerson
    {
        public Guid IdcontactPerson { get; set; }
        public string Name { get; set; } = null!;
        public string Email { get; set; } = null!;
        public string? Phone { get; set; }
        public Guid Idcustomer { get; set; }

        public virtual Customer IdcustomerNavigation { get; set; } = null!;
    }
}

basicCRM/Controllers/ContactPersonController.cs
using basicCRM.Data;
using basicCRM.Repository;
using basicCRM.ViewModels;
using basicCRM.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace basicCRM.Controllers
{
    [Authorize(Roles = "HeadOfSales,Sales,AccountManager")]
    public class ContactPersonController : Controller
    {
        private ContactPersonRepository _contactpersonRepository;
        private CustomerRepository _customerRepository;

        public ContactPersonController(ApplicationDbContext dbcontext)
        {
            _contactpersonRepository = new ContactPersonRepository(dbcontext);
            _customerRepository = new CustomerRepository(dbcontext);    
        }
        // GET: ContactPersonController
        public ActionResult Index(string searchString, int page=1)
        {
            var list = _contactpersonRepository.GetAllContactPersons();
            int pageSize = 4;
            int recordsSkip = (page - 1) * pageSize;
            int recordsCount = list.Count();
            if (!String.IsNullOrEmpty(searchString))
            {
                list = _contactpersonRepository.GetAllContactPersonsFilteredBy(searchString);
                recordsSkip = 0;
            }

           
            var pager = new Pager(recordsCount, page, pageSize);
            this.ViewBag.Pager = pager;

            var viewmodellist = new List<ContactPersonViewModelIndexDetails>();
            foreach (var contactperson in list)
            {
                viewmodellist.Add(new ContactPersonViewModelIndexDetails(contactperson, _customerRepository));
            }
            var data = viewmodellist.Skip(recordsSkip).Take(pager.PageSize);
            return View(data);
        }

        // GET: ContactPersonController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _contactpersonRepository.GetContactPersonById(id);
            var viewmodel = new ContactPersonViewModelIndexDetails(model, _customerRepository);
            return View("DetailsContactPerson",viewmodel);
        }

        // GET: ContactPersonController/Create
        public ActionResult Create()
        {
            var viewmodel = new ContactPersonViewModelCreateEdit(new ContactPersonModel(), _customerRepository);
            return View("CreateContactPerson",viewmodel);
        }

        // POST: ContactPersonController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var model = new ContactPersonModel();
                var task = TryUpdateModelAsync(model);
                if (task.Result)
                {
                    _contactpersonRepository.InsertContactPerson(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("CreateContactPerson");
            }
        }

        // GET: ContactPersonController/Edit/5
        public ActionResult Edit(Guid id)
        {
            var model = _contactpersonRepository.GetContactPersonById(id);
            var viewmodel = new ContactPersonViewModelCreateEdit(model, _customerRepository);
            return View("EditContactPerson",viewmodel);
        }

        // POST: ContactPersonController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, IFormCollection collection)
        {
            try
            {
                var model = new ContactPersonModel();
                var task = TryUpdateModelAsync(model);
                //model.IdcontactPerson=id;
                if (task.Result)
                { 
                _contactpersonRepository.UpdateContactPerson(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("EditContactPerson");
            }
        }

        // GET: ContactPersonController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model= _contactpersonRepository.GetContactPersonById(id);
            var viewmodel = new ContactPersonViewModelCreateEdit(model, _customerRepository);
            return View("DeleteContactPerson",viewmodel);
        }

        // POST: ContactPersonController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                _contactpersonRepository.DeleteContactPerson(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("DeleteContactPerson", id);
            }
        }
    }
}

basicCRM/Views/ContactPerson/CreateContactPerson.cshtml
@model basicCRM.ViewModels.ContactPersonViewModelCreateEdit

@{
    ViewData["Title"] = "CreateContactPerson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Contact Person</h1>

@*<h4>ContactPersonViewModelExtended</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
@*            <div class="form-group">
                <label asp-for="IdcontactPerson" class="control-label"></label>
                <input asp-for="IdcontactPerson" class="form-control" />
                <span asp-validation-for="IdcontactPerson" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Idcustomer" class="control-label"></label>
                <input asp-for="Idcustomer" class="form-control" />
                <span asp-validation-for="Idcustomer" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Customer" class="control-label"></label>
                <select asp-for="Idcustomer" class="form-control" />
                @foreach (var obj in Model.Customers)
                {
                    <option value="@obj.Idcustomer">@obj.Name</option>
                }
                </select>
                <span asp-validation-for="Customer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

basicCRM/Views/ContactPerson/DeleteContactPerson.cshtml
@model basicCRM.ViewModels.ContactPersonViewModelIndexDetails

@{
    ViewData["Title"] = "DeleteContactPerson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete Contact Person</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    @*<h4>ContactPersonViewModel</h4>*@
    <hr />
    <dl class="row">
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdcontactPerson)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdcontactPerson)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idcustomer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idcustomer)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

basicCRM/Views/ContactPerson/DetailsContactPerson.cshtml
@model basicCRM.ViewModels.ContactPersonViewModelIndexDetails

@{
    ViewData["Title"] = "DetailsContactPerson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Contact Person Details</h1>

<div>
    @*<h4>ContactPersonViewModel</h4>*@
    <hr />
    <dl class="row">
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdcontactPerson)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdcontactPerson)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idcustomer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idcustomer)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {id = Model.IdcontactPerson }) |
    <a asp-action="Index">Back to List</a>
</div>

basicCRM/Views/ContactPerson/EditContactPerson.cshtml
@model basicCRM.ViewModels.ContactPersonViewModelCreateEdit

@{
    ViewData["Title"] = "EditContactPerson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Contact Person</h1>

@*<h4>ContactPersonViewModelExtended</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class hidden="form-group">
                <label asp-for="IdcontactPerson" class="control-label"></label>
                <input asp-for="IdcontactPerson" class="form-control" />
                <span asp-validation-for="IdcontactPerson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class hidden="form-group">
                <label asp-for="Idcustomer" class="control-label"></label>
                <input asp-for="Idcustomer" class="form-control" />
                <span asp-validation-for="Idcustomer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer" class="control-label"></label>
                <select asp-for="Idcustomer" class="form-control" />
                @foreach (var obj in Model.Customers)
                {
                    <option value="@obj.Idcustomer">@obj.Name</option>
                }
                </select>
                <span asp-validation-for="Customer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

basicCRM/Views/ContactPerson/Index.cshtml
@model IEnumerable<basicCRM.ViewModels.ContactPersonViewModelIndexDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Pager pager = new Pager();
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
    }
}

<h1>List of Contact Persons</h1>

<p>
    @if (User.IsInRole("AccountManager"))
    {
        <a class="btn btn-primary" asp-action="Create">Create New</a>
    }
</p>
@using (Html.BeginForm())
{
    <p>
        Find by name or email: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer)
            </td>
            <td>
               @if (User.IsInRole("AccountManager"))
                    {
                        @*@Html.ActionLink("Edit", "Edit", new { id=item.IdcontactPerson},new {@class="btn btn-warning"})*@
                        <a href="@Url.Action("Edit","ContactPerson",new { id=item.IdcontactPerson})" ,new class="btn btn-outline-warning">
                            <span>
                                <img src="~/pencil-square.svg" alt="Edit SVG" />
                            </span>
                        </a>

                    }
                    @*@Html.ActionLink("Details", "Details", new { id=item.IdcontactPerson},new {@class="btn btn-info"}) *@
                    <a href="@Url.Action("Details","ContactPerson",new { id=item.IdcontactPerson})" ,new class="btn btn-outline-info">
                        <span>
                            <img src="~/card-heading.svg" alt="Details SVG" />
                        </span>
                    </a>
                    @if (User.IsInRole("AccountManager"))
                    {
                        @*@Html.ActionLink("Delete", "Delete", new { id=item.IdcontactPerson},new {@class="btn btn-danger"})*@
                        <a href="@Url.Action("Delete","ContactPerson",new { id=item.IdcontactPerson})" ,new class="btn btn-outline-danger">
                            <span>
                                <img src="~/trash.svg" alt="Delete SVG" />
                            </span>
                        </a>
                    }

                </td>
        </tr>
}
    </tbody>
</table>

<div class="container">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">

            @if (pager.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-asp-controller="ContactPerson" asp-action="Index" asp-route-page="1">First</a>
                </li>
                <li>
                    <a class=" page-link" asp-asp-controller="ContactPerson" asp-action="Index" asp-route-page="@(pager.CurrentPage-1)">Previous</a>
                </li>
            }

            @for (var pge = 1; pge <= pager.TotalPages; pge++)
            {
                <li class="page-item @(pge==pager.CurrentPage ? "active" : "")">

                    <a class="page-link" asp-controller="ContactPerson" asp-action="Index" asp-route-page="@pge"> @pge </a>
                </li>

            }

            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li class="page-item">
                    <a class=" page-link" asp-asp-controller="ContactPerson" asp-action="Index" asp-route-page="@(pager.CurrentPage+1)">Next</a>
                </li>
                <li>
                    <a class=" page-link" asp-asp-controller="ContactPerson" asp-action="Index" asp-route-page="@(pager.TotalPages)">Last</a>
                </li>

            }

        </ul>

    }

</div>