basicCRM/Controllers/CustomerController.cs
using basicCRM.Repository;
using basicCRM.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using basicCRM.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace basicCRM.Controllers
{
    [Authorize(Roles = "HeadOfSales,Sales,AccountManager")]
    public class CustomerController : Controller
    {
       
        private CustomerRepository _customerRepository;

        public CustomerController(ApplicationDbContext dbcontext)
        { 
        _customerRepository = new CustomerRepository(dbcontext);
        }
        // GET: CustomerController
        public ActionResult Index(string searchString, int page=1)
        {
            var list = _customerRepository.GetAllCustomers();
            int pageSize = 4;

            int recordsSkip = (page - 1) * pageSize;
            int recordsCount = list.Count();
            if (!String.IsNullOrEmpty(searchString))
            {
                list = _customerRepository.GetAllCustomersFilteredBy(searchString);
                recordsSkip = 0;
            }
          
            var pager = new Pager(recordsCount, page, pageSize);
            var data = list.Skip(recordsSkip).Take(pager.PageSize);

            this.ViewBag.Pager = pager;
            return View(data);
        }

        // GET: CustomerController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _customerRepository.GetCustomerById(id);
            return View("DetailsCustomer",model);
        }

        // GET: CustomerController/Create
        [Authorize (Roles ="AccountManager")]
        public ActionResult Create()
        {
            var model = new CustomerModel();
            if(User.Identity.IsAuthenticated)
            {
                model.CreatedBy = User.Identity.Name;   

            }
            return View("CreateCustomer",model);
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var model = new CustomerModel();
                var task = TryUpdateModelAsync(model);
                if (task.Result)
                {
                    _customerRepository.InsertCustomer(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("CreateCustomer");
            }
        }

        // GET: CustomerController/Edit/5
       
        public ActionResult Edit(Guid id)
        {
            var model =_customerRepository.GetCustomerById(id);
            return View("EditCustomer",model);
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Edit(Guid id, IFormCollection collection)
        {
            try
            {
                var model = new CustomerModel();
                var task = TryUpdateModelAsync(model);
                model.Idcustomer= id;
                if (task.Result)
                {
                    _customerRepository.UpdateCustomer(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("EditCustomer");
            }
        }

        // GET: CustomerController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _customerRepository.GetCustomerById(id);
            ViewBag.ErrorMessage = "Acest client este legat de o oportunitate si nu se poate sterge";
            return View("DeleteCustomer",model);
        }

        // POST: CustomerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {

                _customerRepository.DeleteCustomer(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                if (ex.Source != null)
                    Console.WriteLine("Verifica daca acest client este legat de o oportunitate {0}",ex.Source);
                     throw new Exception("Verifica daca acest client este legat de o oportunitate"); 
                                           
            }
            catch
            {
                return View("DeleteCustomer", id);
            }

        }
    }
}

basicCRM/Controllers/EmployeeController.cs
using basicCRM.Data;
using basicCRM.Models;
using basicCRM.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.NetworkInformation;

namespace basicCRM.Controllers
{
    [Authorize(Roles ="HeadOfSales")]
    public class EmployeeController : Controller
    {
        private EmployeeRepository _employeeRepository;

        public List<String> lroles = new List<String>() { "Sales", "AccountManager", "HeadOfSales" };
        public List<String> ldepartments = new List<String>() { "SalesEast", "SalesNorth", "SalesWest", "SalesSouth" };

        public EmployeeController(ApplicationDbContext dbcontext)
        {
            _employeeRepository = new EmployeeRepository(dbcontext);
        }
        // GET: EmployeeController
        public ActionResult Index(string searchString, int page=1)
        {
            var list = _employeeRepository.GetAllEmployees();
            int pageSize = 4;

            int recordsSkip = (page - 1) * pageSize;
            int recordsCount = list.Count();
            if (!String.IsNullOrEmpty(searchString))
            {
                list = _employeeRepository.GetAllEmployeeFilteredBy(searchString);
                recordsSkip = 0;
            }
            
            var pager = new Pager(recordsCount, page, pageSize);
            var data = list.Skip(recordsSkip).Take(pager.PageSize);

            this.ViewBag.Pager = pager;
            return View(data);
        }

        // GET: EmployeeController/Details/5
        public ActionResult Details(Guid id)
        {
        var model = _employeeRepository.GetEmployeeById(id);
            return View("DetailsEmployee",model);
        }

        // GET: EmployeeController/Create
        public ActionResult Create()
        {
            ViewBag.roles = lroles;
            ViewBag.departments = ldepartments;
            return View("CreateEmployee");
        }

        // POST: EmployeeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var model = new EmployeeModel();
                var task = TryUpdateModelAsync(model);
                task.Wait();
                if (task.Result)
                { 
                _employeeRepository.InsertEmployee(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("CreateEmployee");
            }
        }

        // GET: EmployeeController/Edit/5
        public ActionResult Edit(Guid id)
        {
            ViewBag.roles = lroles;
            ViewBag.departments = ldepartments;
            var model = _employeeRepository.GetEmployeeById(id);
            return View("EditEmployee",model);
        }

        // POST: EmployeeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, IFormCollection collection)
        {
            try
            {
                var model = new EmployeeModel();
                var task = TryUpdateModelAsync(model);
                model.Idemployee = id;
                task.Wait();
                if (task.Result)
                {
                    _employeeRepository.UpdateEmployee(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("EditEmployee");
            }
        }

        // GET: EmployeeController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _employeeRepository.GetEmployeeById(id);
            ViewBag.ErrorMessage = "Acest angajat este relationat de o oportunitate/oferta/client si nu se poate sterge";
            return View("DeleteEmployee",model);
        }

        // POST: EmployeeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
              _employeeRepository.DeleteEmployee(id);
                ViewBag.ErrorMessage = "Acest angajat este relationat de o oportunitate/oferta/client si nu se poate sterge";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("DeleteEmployee", id);
            }
        }
    }
}

basicCRM/Controllers/OfferController.cs
using basicCRM.Data;
using basicCRM.Repository;
using basicCRM.ViewModels;
using basicCRM.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace basicCRM.Controllers
{
    [Authorize(Roles = "HeadOfSales,Sales,AccountManager")]
    public class OfferController : Controller
    {
        private OfferRepository _offerRepository;
        private EmployeeRepository _employeeRepository;
        private OpportunityRepository _opportunityRepository;

        public List<String> loffertypes = new List<String>() { "Binding", "Indicative"};

        public OfferController(ApplicationDbContext _DBContext)
        { 
            _offerRepository = new OfferRepository(_DBContext);
            _employeeRepository = new EmployeeRepository(_DBContext);
            _opportunityRepository=new OpportunityRepository(_DBContext);
        }
        // GET: OfferController
        public ActionResult Index(string searchString, int page = 1)
        {
            var list=_offerRepository.GetAllOffers();
            int pageSize = 4;

            int recordsSkip = (page - 1) * pageSize;
            int recordsCount = list.Count();
            if (!String.IsNullOrEmpty(searchString))
            {
                list = _offerRepository.GetAllOffersFilteredBy(searchString);
                recordsSkip = 0;
            }
            var viewmodellist = new List<OfferViewModelIndexDetails>();
            foreach (var offer in list)
            {
                viewmodellist.Add(new OfferViewModelIndexDetails(offer, _opportunityRepository, _employeeRepository));
            }
            var pager = new Pager(recordsCount, page, pageSize);
            var data = viewmodellist.Skip(recordsSkip).Take(pager.PageSize);

            this.ViewBag.Pager = pager;
            return View(data);
        }

        // GET: OfferController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _offerRepository.GetOfferById(id);
            var viewmodel = new OfferViewModelIndexDetails(model, _opportunityRepository, _employeeRepository);
            return View("DetailsOffer",viewmodel);
        }

        // GET: OfferController/Create
        public ActionResult Create()
        {
            ViewBag.offertypes=loffertypes;
            var viewmodel = new OfferViewModelCreateEdit(new OfferModel(), _opportunityRepository, _employeeRepository);
            return View("CreateOffer",viewmodel);
        }

        // POST: OfferController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var model = new OfferModel();
                var task = TryUpdateModelAsync(model);
                if (task.Result)
                {
                    _offerRepository.InsertOffer(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("CreateOffer");
            }
        }

        // GET: OfferController/Edit/5
        public ActionResult Edit(Guid id)
        {
            ViewBag.offertypes = loffertypes;
            var model = _offerRepository.GetOfferById(id);
            var viewmodel = new OfferViewModelCreateEdit(model, _opportunityRepository, _employeeRepository); 
            return View("EditOffer",viewmodel);
        }

        // POST: OfferController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, IFormCollection collection)
        {
            try
            {
                var model = new OfferModel();
                var task = TryUpdateModelAsync(model);
                if (task.Result)
                {
                    _offerRepository.UpdateOffer(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("EditOffer");
            }
        }

        // GET: OfferController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _offerRepository.GetOfferById(id);
            var viewmodel= new OfferViewModelCreateEdit(model, _opportunityRepository, _employeeRepository);
            return View("DeleteOffer",viewmodel);
        }

        // POST: OfferController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                _offerRepository.DeleteOffer(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("DeleteOffer", id);
            }
        }
    }
}

basicCRM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - basicCRM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/basicCRM.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
               @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">basicCRM</a>*@
                <a class="navbar-brand" href="h">
                    <img src=/CRM-Mag-Logo.png alt="basicCRM" width="120" height="50">
                    <a/>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Opportunity" asp-action="Index">Opportunity</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Offer" asp-action="Index">Offer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContactPerson" asp-action="Index">ContactPerson</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - basicCRM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>